# locust.conf - Configuración por defecto para ejecución de pruebas de carga
locustfile = tests/performance/locustfile.py
host = http://localhost:5002
headless = true
users = 50
spawn-rate = 5
run-time = 1m
html = tests/performance/report_locust.html
csv = tests/performance/locust_stats
